/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      colors: {
        background: '#0b1326',
        primary: '#c0c1ff',
        'primary-container': '#8083ff',
        'primary-fixed': '#e1e0ff',
        'primary-fixed-dim': '#c0c1ff',
        secondary: '#c0c1ff',
        'secondary-container': '#42447b',
        'secondary-fixed': '#e1e0ff',
        'secondary-fixed-dim': '#c0c1ff',
        tertiary: '#ffb783',
        'tertiary-container': '#d97721',
        'tertiary-fixed': '#ffdcc5',
        'tertiary-fixed-dim': '#ffb783',
        surface: '#0b1326',
        'surface-variant': '#2d3449',
        'surface-bright': '#31394d',
        'surface-dim': '#0b1326',
        'surface-container': '#171f33',
        'surface-container-low': '#131b2e',
        'surface-container-lowest': '#060e20',
        'surface-container-high': '#222a3d',
        'surface-container-highest': '#2d3449',
        'surface-tint': '#c0c1ff',
        outline: '#908fa0',
        'outline-variant': '#464554',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'inverse-surface': '#dae2fd',
        'inverse-on-surface': '#283044',
        'inverse-primary': '#494bd6',
        'on-background': '#dae2fd',
        'on-primary': '#1000a9',
        'on-primary-container': '#0d0096',
        'on-primary-fixed': '#07006c',
        'on-primary-fixed-variant': '#2f2ebe',
        'on-secondary': '#292a60',
        'on-secondary-container': '#b2b3f2',
        'on-secondary-fixed': '#13144a',
        'on-secondary-fixed-variant': '#404178',
        'on-tertiary': '#4f2500',
        'on-tertiary-container': '#452000',
        'on-tertiary-fixed': '#301400',
        'on-tertiary-fixed-variant': '#703700',
        'on-surface': '#dae2fd',
        'on-surface-variant': '#c7c4d7',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        'xl': '1.5rem',
        'full': '9999px',
        'md': '0.75rem',
      },
    },
  },
  plugins: [],
}
